services:
  postgresql:
    image: "ankane/pgvector"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6000:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"